In [4]:
import pandas as pd
import numpy as np
import time
from bs4 import BeautifulSoup
import requests
import nltk 

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk import word_tokenize
import string
from nltk.tokenize import RegexpTokenizer
#download the stop words
nltk.download("stopwords")
import json
import math

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\elena\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
 def Objective_page(url):
    try:
        tag=BeautifulSoup(requests.get(url).text, "html.parser")
        time.sleep(2)
        l1=['piano','bagni','superficie','locali']
        df=[]
        x=tag.findAll('div',{'class':'im-property__features'})
        y=tag.findAll('div',{'class':'clearfix description'})
        d={}
        house=[text for text in x[0].stripped_strings]
        house.reverse()
        house1=[text for text in y[0].stripped_strings]
        house1=" ".join(house1)
        for i in l1:
            if i in house:
                index=house.index(i)
                if i=='superficie':
                    d[i]=house[index+3]
                else:
                    d[i]=house[index+1]
                if house[-1].find('€')!=-1:
                    d['prezzo(€)']=house[-1]
        d['description']=house1
    except:
        d['description']="there was a problem in this link"
    del tag
    return(d)

In [6]:
link=pd.read_csv("Scrappinglink.csv")
l=list(link["links"])

In [ ]:
from multiprocessing import Pool
with Pool(10) as p:
    records = p.map(Objective_page, l[5000:7000])
p.terminate()
p.join()

In [3]:
df1=pd.read_csv('first-Scraping.csv')
df2=pd.read_csv('2rd_scaping_1.csv')
df3=pd.read_csv('3rd_scaping_1.csv')


All the data frame was preprocessed by

1) Removing stop words

2) Removing punctuation

3) Stemming

4) Tokenization

To make our computational steps faster we applied the preprocessing only to description and title columns

In [6]:
finaldf = pd.concat([df1,df2,df3])
finaldf=finaldf.reset_index(drop=True)
finaldf.drop(['Unnamed: 0'], axis=1)

,bagni,description,locali,piano,prezzo(€),superficie
0,NaN,Vendesi Appartamenti - Talenti Rione Rinascime...,1 - 5,NaN,€ 192.000 - € 705.000,46.0
1,1,papillo eur PAPILLO EUR in elegante complesso ...,2,1,€ 225.000,50.0
2,1,VENDITA BILOCALE TORREVECCHIA Rif: 18083 - TOR...,2,R,€ 159.000,65.0
3,1,"San Giovanni San Giovanni, Attico in Vendita, ...",2,A,€ 459.000,85.0
4,2,ATTICO CON TERRAZZO VILLA PAMPHILI Nel quartie...,5,A,€ 850.000,175.0
5,3+,Gregorio Settimo - San Damaso Gregorio Settimo...,5+,3,€ 1.100.000,225.0
6,1,VENDITA TRILOCALE RISTRUTTURATO CASILINA Rif: ...,3,2,€ 119.000,85.0
7,1,VENDITA TRILOCALE CENTOCELLE Rif: 18067 - CENT...,3,1,€ 149.000,75.0
8,3+,Elegante villa stile Liberty a San Giovanni A ...,5+,NaN,€ 2.500.000,625.0
9,2,PRATI- DELLE VITTORIE PIAZZALE CLODIO Siamo a ...,4,9,€ 1.300.000,115.0
10,1,VENDITA BILOCALE TORRE MAURA Rif: 18028 - TORR...,2,3,€ 115.000,58.0
11,3,Elegante appartamento zona Monteverde Nel quar...,5+,3,€ 695.000,250.0
12,2,PRESTIGIOSO UFFICIO PIAZZALE DELLE MUSE Nell’e...,5+,T,€ 1.220.000,245.0
13,2,Porzione di villino stile Liberty adiacente il...,5+,2,€ 1.380.000,140.0
14,2,Ampio appartamento in via Bruno Pelizzi In zon...,4,5,€ 370.000,139.0
15,3,VENDITA QUADRILOCALE RISTRUTTURATO PISANA Rif:...,4,3,€ 359.000,130.0
16,3,COMPLESSO RESIDENZIALE LEONARDO DA VINCI a sol...,4,NaN,€ 219.000,160.0
17,3,PRESTIGIOSO APPARTAMENTO VIA COURMAYEUR Via Co...,5+,1,€ 650.000,170.0
18,3,"CAMILLUCCIA, PANORAMICO QUARTO PIANO In strada...",5+,4,€ 800.000,220.0
19,3,Appartamento ristrutturato in via del Calice I...,5+,4,€ 650.000,193.0
20,1,Elegante bilocale nel cuore di San Giovanni In...,2,3,€ 339.000,70.0
21,3+,Moderno Appartamento con Terrazzo in Viale del...,5+,1,€ 1.100.000,250.0
22,1,"Prati Prati, appartamento in vendita adiacente...",5,3,€ 950.000,170.0
23,3,Rifinito attico e superattico in Via Pound Nel...,5+,A,€ 940.000,200.0
24,1,"Montagnola Montagnola, Appartamento in Vendita...",2,A,€ 259.000,55.0
25,2,Roma case in vendita Appio Claudio quadrilocal...,4,1,€ 460.000,110.0
26,1,VENDITA ULTIMO PIANO RISTRUTTURATO CASILINA Ri...,3,A,€ 165.000,60.0
27,2,"Collatina Collatina, Attico in Vendita, tranqu...",4,A,€ 189.000,110.0
28,3+,Elegante appartamento panoramico in zona Baldu...,5+,3,€ 1.080.000,250.0
29,2,"Nomentana Nomentana – in via di Pietralata, a ...",5+,1,€ 395.000,130.0
...,...,...,...,...,...,...
14970,1,Trionfale Rif: gruppoimmobiliare - Via Cortina...,4,2,€ 650.000,165.0
14971,2,"APPARTAMENTO IN VENDITA DI 158 MQ, ZONA TALENT...",5,T,€ 520.000,158.0
14972,NaN,there was a problem in this link,NaN,NaN,NaN,NaN
14973,1,"Roma, Settebagni, precisamente in via Sant'Ant...",3,R,€ 200.000,80.0
14974,2,EUR CECCHIGNOLA APPARTAMENTO A SCHIERA CON GIA...,4,R,da € 220.534,150.0
14975,1,PRATI/DELLE VITTORIE-QUADRILOCALE TERMOAUTONOM...,5+,2,€ 689.000,148.0
14976,1,Monteverde-Colli Portuensi ampio trilocale con...,3,T,€ 355.000,104.0
14977,2,TORRE SPACCATA Via Rugantino vendita appartame...,3,1,€ 265.000,90.0
14978,2,San Giovanni Rif: gruppo immobiliare - adiac. ...,5+,6,€ 860.000,200.0
14979,2,"Piena proprietà di appartamento, via Dei Gelsi...",4,3,da € 98.250,136.0
14980,2,Parchi della colombo Rif: gruppo immobiliare -...,3,NaN,€ 359.000,90.0
14981,1,Cinecittà Rif: GRUPPO IMMOBILIARE - via Chiove...,3,7,€ 270.000,90.0
14982,1,Bilocale 60 mq con balconi APM IMMOBILIARE TEL...,2,1,€ 139.000,60.0
14983,2,NUDA PROPRIETA' In una delle strade più piacev...,5+,5,€ 1.200.000,200.0
14984,1,Centro Storico - Palazzo Umbertino Centro Stor...,3,2,€ 329.000,90.0
14985,2,ROMA - TUSCOLANO - Cinecittà Abbiamo il piacer...,5+,2,€ 560.000,200.0
14986,2,PONTE MILVIO TRILOCALE RIFINITURE LUSSO € 390....,3,1,€ 390.000,75.0
14987,2,Quadrilocale di 140 mq. Ostia Centro APPARTAME...,3,2,€ 329.000,143.0
14988,3,Rif: Patrasso - DRAGONCELLO Via Leonardo Patra...,5,NaN,€ 340.000,168.0
14989,2,DUE LEONI In delizioso complesso residenziale ...,3,1,€ 165.000,86.0
14990,2,bravetta In una delle strade più ambite della ...,3,3,€ 370.000,103.0
14991,2,PARIOLI - TRILOCALE RISTRUTTURATO GIARDINO E C...,3,1,€ 670.000,116.0
14992,2,Nuova costruzione Vicolo del Conte - Casetta...,3,T,€ 345.000,96.0
14993,3,BOLOGNA - VIALE XXI APRILE - A pochi passi da ...,5+,2,€ 950.000,190.0
14994,2,Appio Latino esclusivo cinque locali LA SCHEMA...,5,3,€ 600.000,162.0
14995,1,CASALOTTI-VIA DORZANO Casalotti-Via Dorzano Ne...,3,3,€ 179.000,65.0
14996,1,CIPRO - BILOCALE ULTIMO PIANO RISTRUTTURATO CO...,2,7,€ 339.000,60.0
14997,1,San Paolo Rif: gruppo immobiliare - Viale Leon...,3,1,€ 470.000,100.0
14998,1,Gruppo Immobiliare 2000 propone in vendita in ...,2,1,€ 129.000,45.0
14999,3+,PIGNETO villini Via Cristoforo Buondelmonti Ri...,5+,NaN,€ 1.400.000,283.0

In [18]:
df=finaldf.dropna()
informationdf=df[['bagni','locali','piano','prezzo(€)','superficie']]
descriptiondf=df[['description']]

In [7]:
stopwords = stopwords.words('italian')

In [8]:
df.description = df.description.apply(str).apply(tokenizer.tokenize)
df.description = df.description.apply(lambda x : [item for item in x if item not in stopwords])
df.description = df.description.apply(lambda x : [st.stem(y) for y in x])